### ISSUE TITLE
robot not moving

### ISSUE THREAD

**Issue by raimohanska** [mirobot/mirobot-pcb#5]
Just received and assembled my Mirobot. I can connect and even make the pen servo and beeper work, but the main steppers won't move. I don't think there's any way to connect them wrong, because the stepper cables only fit in one way. What now?

**Comment by bjpirt** [comment]
Strange that the servo works but the steppers don't. I wonder if you might be able to send a photo of the main controller board to info@mirobot.io so I can see if there's anything obviously wrong. Otherwise I'll sort you out with a replacement.
